# Generated by Django 3.2.20 on 2023-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='aboutAuthor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
