# Generated by Django 3.2.20 on 2023-08-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
                ('pages_number', models.PositiveSmallIntegerField()),
                ('volume_year', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
