# Generated by Django 3.2.20 on 2023-08-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreation', models.DateField(auto_now_add=True)),
                ('label', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.volume')),
            ],
        ),
    ]
