# Generated by Django 3.2.20 on 2023-09-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20230901_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
