# Generated by Django 3.2.20 on 2023-09-10 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_typesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('year_publication', models.DateField()),
                ('editor', models.CharField(max_length=255)),
                ('type_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.typesource')),
            ],
        ),
    ]
