# Generated by Django 3.2.20 on 2023-09-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='year_publication',
            field=models.DateField(blank=True, null=True),
        ),
    ]
