# Generated by Django 3.2.20 on 2023-09-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20230910_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='year_publication',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
