# Generated by Django 3.2.20 on 2023-09-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_source_year_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.typesource'),
        ),
    ]
