# Generated by Django 3.2.20 on 2023-09-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0010_alter_source_type_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_ang', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_accept', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('abstract_fr', models.TextField()),
                ('abstract_ang', models.TextField(blank=True, null=True)),
                ('file_submit', models.FileField(blank=True, null=True, upload_to='files-submit/articles')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='files-submit/articles')),
                ('keywords_fr', models.TextField()),
                ('keywords_ang', models.TextField()),
                ('state', models.IntegerField(choices=[(1, 'Initialisation'), (2, 'Parrution'), (3, 'Publication')], default=1)),
                ('page_begin', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('doi_link', models.TextField()),
                ('orcid_link', models.CharField(max_length=255)),
                ('counter_download', models.IntegerField()),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='pictures/articles-cover')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.numero')),
            ],
        ),
    ]
