# Generated by Django 3.2.20 on 2023-09-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='type_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='review.typesource'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('page_begin', models.IntegerField(blank=True, null=True)),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('edition_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ManyToManyField(related_name='refrences', to='review.Article')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='review.source')),
            ],
        ),
    ]
