# Generated by Django 3.2.20 on 2023-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20230917_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.ManyToManyField(to='review.Reference'),
        ),
    ]
