# Generated by Django 3.2.20 on 2023-09-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_alter_article_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.numero'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_begin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
