# Generated by Django 3.2.20 on 2023-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_auto_20230918_1813'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='numero',
            name='unique_numero_by_volume',
        ),
        migrations.AlterField(
            model_name='numero',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
